### ISSUE TITLE
http connection pooling

### ISSUE THREAD

**Issue by toshok** [honeycombio/libhoney-rb#3]
If http.rb (https://github.com/httprb/http) supports persistent http connections, it's likely worth it to reuse connections for sending events to the same server.

Since the `api_host` can vary from event to event, we'll need to be able to keep several connections around.  Also, it's probably going to be insanely uncommon for `api_host` to vary at all, so we'll need to support multiple connections to the same host, probably per-thread.

**Comment by robbkidd** [comment]
Overcome by events. libhoney-rb [replaced http.rb with Excon](https://github.com/honeycombio/libhoney-rb/pull/81) for HTTP connections which are also now persistent and managed per API host.
