### ISSUE TITLE
Segfault under load

### ISSUE THREAD

**Issue by DanielHeath** [honeycombio/libhoney-rb#41]
This worked nicely in staging for us, but under production load it took the site down - every instance segfaulted after serving a few hundred requests!

```
uname -a
Linux radiopaedia-website-production-web-i-00658096f2470d21e 3.13.0-164-generic #214-Ubuntu SMP Wed Dec 5 10:42:33 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
/libhoney-1.12.1/lib/libhoney/transmission.rb:38: [BUG] Segmentation fault at 0x00007fddc2000a30
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
```

Will post more details as I find them...

**Comment by nathanleclaire** [comment]
Sorry to hear! Thanks for the report. We'll look into it soon.

**Comment by martin308** [comment]
@DanielHeath that's not good! Can you tell me a bit more about your setup? Are you running puma or similar in production? Feel free to email the details if you don't want to publicly post anything martin@honeycomb.io

**Comment by DanielHeath** [comment]
Sure. 

 * Only web instances crashed - worker and cron instances were unaffected, as were all staging instances (leading me to believe it's load-related - worker/cron instances don't see much load).
 * Web instances run nginx -> domain socket -> unicorn master -> 8 unicorn workers.

Is there an ASAN-enabled build of `libhoney` available? I think I could convince work to run a canary instance, and having address sanitisation enabled should give an actionable crash dump.

**Comment by martin308** [comment]
@DanielHeath we don't have any native code in `libhoney` that we could build to provide this. 

Is that the entire stack trace that you have posted? What other dependencies do you have? How are you initialising the beeline (or are you just using libhoney?) I've tried to reproduce this with a Sinatra app with 4 workers and 32 threads per worker with a load test and have had no luck so far 😢

**Comment by DanielHeath** [comment]
I haven't been able to reproduce it in staging under high load, either. Will try and get a canary instance running in production.

**Comment by DanielHeath** [comment]
Have emailed a detailed trace.

**Comment by DanielHeath** [comment]
Upgrading from ruby 2.5.3 to 2.6.3 has resolved this issue.

**Comment by martin308** [comment]
Just in case anyone else wanders in here. This is the issue that I believe that @DanielHeath encountered https://bugs.ruby-lang.org/issues/14634
