### ISSUE TITLE
Client#close does not claim queue

### ISSUE THREAD

**Issue by ryanking** [honeycombio/libhoney-rb#8]
Example says:

> \# Call close to flush any pending calls to Honeycomb

Yet the `drain` param on the `#close` method defaults to false, which means that when we get [here](https://github.com/honeycombio/libhoney-rb/blob/master/lib/libhoney/transmission.rb#L71) the queue will not be drained but discarded.

So, if you follow the example you have a race condidtion.

I would suggest that either `#drain` should default to `true` or there should be a separate method for draining vs closing.

**Comment by ryanking** [comment]
I would have opened a PR but not sure your preference on the semantic change.

**Comment by ryanking** [comment]
Not that this is not a hypothetical problem (if you follow the example, which I did). See here where I deployed my workaround:

![screen shot 2017-04-08 at 9 25 49 pm](https://cloud.githubusercontent.com/assets/5640/24834701/07cb7ce0-1ca2-11e7-8610-621b74ab19f4.png)

Pretty clear that I was losing data.

**Comment by toshok** [comment]
should be fixed (defaulting to `drain=true` as you suggested).  Thanks for the report!
